name: flutter_simple_calculator
description: Flutter widget that provides simple calculator. You can easily integrate a calculator to your apps.
version: 2.2.1
homepage: https://github.com/zuvola/flutter_simple_calculator

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  flutter_grid_button: ^2.0.0
  auto_size_text: ^3.0.0
  expressions: ^0.2.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
