name: flutter_simple_calculator
description: Flutter widget that provides simple calculator. You can easily integrate a calculator to your apps.
version: 2.2.5
homepage: https://github.com/zuvola/flutter_simple_calculator

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_grid_button: ^2.1.0
  auto_size_text: ^3.0.0
  expressions: ^0.2.5+1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
